<script setup lang="ts">
import { Button as _AButtonImpl, Drawer as _ADrawerImpl, Form as _AFormImpl, FormItem as _AFormItemImpl, Input as _AInputImpl, InputNumber as _AInputNumberImpl, Pagination as _APaginationImpl, Segmented as _ASegmentedImpl, Select as _ASelectImpl, Table as _ATableImpl } from 'ant-design-vue'
const AButton: any = _AButtonImpl
const ADrawer: any = _ADrawerImpl
const AForm: any = _AFormImpl
const AFormItem: any = _AFormItemImpl
const AInput: any = _AInputImpl
const AInputNumber: any = _AInputNumberImpl
const APagination: any = _APaginationImpl
const ASegmented: any = _ASegmentedImpl
const ASelect: any = _ASelectImpl
const ATable: any = _ATableImpl
import { onMounted, reactive, ref } from 'vue'
import { message, Modal } from 'ant-design-vue'
import PageHeader from '../components/PageHeader.vue'
import { apiRequest } from '../api/client'
import { usePagedList } from '../composables/usePagedList'
import { DeleteOutlined, PauseOutlined, PlayCircleOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons-vue'
const list=usePagedList('/api/scheduler/',{name:''});const selected=ref<string[]>([]);const open=ref(false);const saving=ref(false);const scopes=ref<any[]>([]);const policies=ref<any[]>([]);const form=reactive({monitor_type:'domain',scope_id:'',domain:'',interval:86400,name:'',policy_id:''})
async function refs(){const [s,p]=await Promise.all([apiRequest<any>('/api/asset_scope/?page=1&size=100'),apiRequest<any>('/api/policy/?page=1&size=100')]);scopes.value=s.items||[];policies.value=p.items||[]}
async function create(){if(!form.scope_id)return message.error('请选择资产组');if(form.monitor_type==='domain'&&!form.domain.trim())return message.error('请输入监控目标');if(form.interval<21600)return message.error('监控间隔不能短于 6 小时');saving.value=true;try{let endpoint='/api/scheduler/add/';let body:any={scope_id:form.scope_id,interval:form.interval,name:form.name};if(form.monitor_type==='domain'){body.domain=form.domain;body.policy_id=form.policy_id}else endpoint=form.monitor_type==='site'?'/api/scheduler/add/site_monitor/':'/api/scheduler/add/wih_monitor/';await apiRequest(endpoint,{method:'POST',body:JSON.stringify(body)});message.success('监控已创建');open.value=false;await list.search()}catch(e){message.error((e as Error).message)}finally{saving.value=false}}
async function operate(action:'stop'|'recover'){if(!selected.value.length)return;await apiRequest(`/api/scheduler/${action}/batch`,{method:'POST',body:JSON.stringify({job_id:selected.value})});message.success(action==='stop'?'监控已停止':'监控已恢复');selected.value=[];await list.load()}
function remove(){Modal.confirm({title:`删除 ${selected.value.length} 个监控？`,okType:'danger',async onOk(){await apiRequest('/api/scheduler/delete/',{method:'POST',body:JSON.stringify({job_id:selected.value})});selected.value=[];await list.load()}})}
onMounted(()=>{list.load();refs().catch(()=>{})})
</script>
<template><section class="page"><PageHeader eyebrow="AUTOMATION / MONITOR" title="资产监控" description="管理域名侦察、站点更新和 Web 信息猎手周期监控；最短间隔为 6 小时。"><a-button @click="list.load"><ReloadOutlined/>刷新</a-button><a-button @click="operate('stop')" :disabled="!selected.length"><PauseOutlined/>停止</a-button><a-button @click="operate('recover')" :disabled="!selected.length"><PlayCircleOutlined/>恢复</a-button><a-button danger @click="remove" :disabled="!selected.length"><DeleteOutlined/>删除</a-button><a-button type="primary" @click="open=true;refs()"><PlusOutlined/>新建监控</a-button></PageHeader><div class="data-panel"><div class="query-strip"><a-input v-model:value="list.filters.name" placeholder="监控名称" allow-clear @press-enter="list.search"/><a-button @click="list.search">筛选</a-button><span><b>{{list.total}}</b> 个监控</span></div><a-table :data-source="list.rows" :loading="list.loading" row-key="_id" :pagination="false" :row-selection="{selectedRowKeys:selected,onChange:(keys:(string|number)[])=>selected=keys.map(String)}" :columns="[{title:'名称',dataIndex:'name'},{title:'目标',dataIndex:'domain'},{title:'类型',dataIndex:'monitor_type'},{title:'状态',dataIndex:'status'},{title:'间隔（秒）',dataIndex:'interval'},{title:'下次执行',dataIndex:'next_run_date'}]"/><a-pagination :current="list.page" :page-size="list.size" :total="list.total" show-size-changer @change="list.changePage"/></div><a-drawer v-model:open="open" title="新建资产监控" width="min(620px,94vw)"><a-form layout="vertical" @finish="create"><a-form-item label="监控类型" required><a-segmented v-model:value="form.monitor_type" :options="[{label:'域名侦察',value:'domain'},{label:'站点更新',value:'site'},{label:'信息猎手',value:'wih'}]" block/></a-form-item><a-form-item label="资产组" required><a-select v-model:value="form.scope_id" show-search option-filter-prop="label" :options="scopes.map(x=>({value:x._id,label:`${x.name} · ${x.scope}`}))"/></a-form-item><a-form-item v-if="form.monitor_type==='domain'" label="监控目标" required extra="必须属于所选资产组；逗号分隔"><a-input v-model:value="form.domain"/></a-form-item><a-form-item label="名称"><a-input v-model:value="form.name"/></a-form-item><a-form-item label="执行间隔（秒）" required><a-input-number v-model:value="form.interval" :min="21600" style="width:100%"/></a-form-item><a-form-item v-if="form.monitor_type==='domain'" label="扫描策略"><a-select v-model:value="form.policy_id" allow-clear :options="policies.map(x=>({value:x._id,label:x.name}))"/></a-form-item><div class="drawer-actions"><a-button @click="open=false">取消</a-button><a-button type="primary" html-type="submit" :loading="saving">创建</a-button></div></a-form></a-drawer></section></template>
