<script setup lang="ts">
import { Button as _AButtonImpl, Drawer as _ADrawerImpl, Form as _AFormImpl, FormItem as _AFormItemImpl, Input as _AInputImpl, Pagination as _APaginationImpl, Segmented as _ASegmentedImpl, Select as _ASelectImpl, Table as _ATableImpl, Textarea as _ATextareaImpl } from 'ant-design-vue'
const AButton: any = _AButtonImpl
const ADrawer: any = _ADrawerImpl
const AForm: any = _AFormImpl
const AFormItem: any = _AFormItemImpl
const AInput: any = _AInputImpl
const APagination: any = _APaginationImpl
const ASegmented: any = _ASegmentedImpl
const ASelect: any = _ASelectImpl
const ATable: any = _ATableImpl
const ATextarea: any = _ATextareaImpl
import { onMounted, reactive, ref } from 'vue'
import { message, Modal } from 'ant-design-vue'
import PageHeader from '../components/PageHeader.vue'
import { apiRequest } from '../api/client'
import { usePagedList } from '../composables/usePagedList'
import { DeleteOutlined, PauseOutlined, PlayCircleOutlined, PlusOutlined } from '@ant-design/icons-vue'
const list=usePagedList('/api/task_schedule/',{name:'',schedule_status:''});const selected=ref<string[]>([]);const open=ref(false);const policies=ref<any[]>([]);const saving=ref(false);const form=reactive({name:'',target:'',schedule_type:'recurrent_scan',policy_id:'',cron:'0 2 * * *',start_date:'',task_tag:'task'})
async function loadPolicies(){const data=await apiRequest<any>('/api/policy/?page=1&size=100');policies.value=data.items||[]}
async function create(){if(!form.name.trim()||!form.target.trim()||!form.policy_id)return message.error('请填写名称、目标并选择策略');if(form.schedule_type==='recurrent_scan'&&!form.cron.trim())return message.error('请输入 Cron 表达式');if(form.schedule_type==='future_scan'&&!form.start_date.trim())return message.error('请输入未来开始时间');saving.value=true;try{await apiRequest('/api/task_schedule/',{method:'POST',body:JSON.stringify(form)});message.success('计划任务已创建');open.value=false;await list.search()}catch(e){message.error((e as Error).message)}finally{saving.value=false}}
async function operate(action:'stop'|'recover'){await apiRequest(`/api/task_schedule/${action}/`,{method:'POST',body:JSON.stringify({_id:selected.value})});message.success(action==='stop'?'计划已停止':'计划已恢复');selected.value=[];await list.load()}
function remove(){Modal.confirm({title:`删除 ${selected.value.length} 个计划任务？`,okType:'danger',async onOk(){await apiRequest('/api/task_schedule/delete/',{method:'POST',body:JSON.stringify({_id:selected.value})});selected.value=[];await list.load()}})}
onMounted(()=>{list.load();loadPolicies().catch(()=>{})})
</script>
<template><section class="page"><PageHeader eyebrow="AUTOMATION / SCHEDULE" title="计划任务" description="按未来时间或 Cron 周期使用指定策略运行资产发现和风险巡航。"><a-button :disabled="!selected.length" @click="operate('stop')"><PauseOutlined/>停止</a-button><a-button :disabled="!selected.length" @click="operate('recover')"><PlayCircleOutlined/>恢复</a-button><a-button danger :disabled="!selected.length" @click="remove"><DeleteOutlined/>删除</a-button><a-button type="primary" @click="open=true;loadPolicies()"><PlusOutlined/>新建计划</a-button></PageHeader><div class="data-panel"><div class="query-strip"><a-input v-model:value="list.filters.name" placeholder="计划名称" @press-enter="list.search"/><a-select v-model:value="list.filters.schedule_status" allow-clear placeholder="全部状态" :options="['scheduled','stop','done'].map(value=>({value}))"/><a-button @click="list.search">筛选</a-button><span><b>{{list.total}}</b> 个计划</span></div><a-table :data-source="list.rows" :loading="list.loading" row-key="_id" :pagination="false" :row-selection="{selectedRowKeys:selected,onChange:(keys:(string|number)[])=>selected=keys.map(String)}" :columns="[{title:'名称',dataIndex:'name'},{title:'目标',dataIndex:'target'},{title:'策略',dataIndex:'policy_name'},{title:'类型',dataIndex:'schedule_type'},{title:'Cron / 时间',key:'time'},{title:'状态',dataIndex:'status'},{title:'下次执行',dataIndex:'next_run_date'}]"><template #bodyCell="{column,record}"><span v-if="column.key==='time'">{{record.cron||record.start_date||'—'}}</span></template></a-table><a-pagination :current="list.page" :page-size="list.size" :total="list.total" @change="list.changePage"/></div><a-drawer v-model:open="open" title="新建计划任务" width="min(640px,94vw)"><a-form layout="vertical" @finish="create"><div class="form-grid"><a-form-item label="名称" required><a-input v-model:value="form.name"/></a-form-item><a-form-item label="任务类别" required><a-select v-model:value="form.task_tag" :options="[{value:'task',label:'资产发现'},{value:'risk_cruising',label:'风险巡航'}]"/></a-form-item></div><a-form-item label="目标" required><a-textarea v-model:value="form.target" :rows="4"/></a-form-item><a-form-item label="策略" required><a-select v-model:value="form.policy_id" :options="policies.map(x=>({value:x._id,label:x.name}))"/></a-form-item><a-form-item label="计划类型" required><a-segmented v-model:value="form.schedule_type" :options="[{value:'recurrent_scan',label:'周期任务'},{value:'future_scan',label:'单次未来任务'}]"/></a-form-item><a-form-item v-if="form.schedule_type==='recurrent_scan'" label="Cron" required extra="周期不得短于系统安全限制"><a-input v-model:value="form.cron"/></a-form-item><a-form-item v-else label="开始时间" required extra="格式：YYYY-MM-DD HH:mm:ss"><a-input v-model:value="form.start_date"/></a-form-item><div class="drawer-actions"><a-button @click="open=false">取消</a-button><a-button type="primary" html-type="submit" :loading="saving">创建</a-button></div></a-form></a-drawer></section></template>
