<script setup lang="ts">
import { Button as _AButtonImpl, Checkbox as _ACheckboxImpl, Divider as _ADividerImpl, Drawer as _ADrawerImpl, Dropdown as _ADropdownImpl, Form as _AFormImpl, FormItem as _AFormItemImpl, Input as _AInputImpl, Menu as _AMenuImpl, MenuItem as _AMenuItemImpl, Modal as _AModalImpl, Pagination as _APaginationImpl, Segmented as _ASegmentedImpl, Select as _ASelectImpl, Space as _ASpaceImpl, Switch as _ASwitchImpl, Table as _ATableImpl, Tag as _ATagImpl, Textarea as _ATextareaImpl } from 'ant-design-vue'
const AButton: any = _AButtonImpl
const ACheckbox: any = _ACheckboxImpl
const ADivider: any = _ADividerImpl
const ADrawer: any = _ADrawerImpl
const ADropdown: any = _ADropdownImpl
const AForm: any = _AFormImpl
const AFormItem: any = _AFormItemImpl
const AInput: any = _AInputImpl
const AMenu: any = _AMenuImpl
const AMenuItem: any = _AMenuItemImpl
const AModal: any = _AModalImpl
const APagination: any = _APaginationImpl
const ASegmented: any = _ASegmentedImpl
const ASelect: any = _ASelectImpl
const ASpace: any = _ASpaceImpl
const ASwitch: any = _ASwitchImpl
const ATable: any = _ATableImpl
const ATag: any = _ATagImpl
const ATextarea: any = _ATextareaImpl
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import PageHeader from '../components/PageHeader.vue'
import { apiRequest, downloadRequest, queryString } from '../api/client'
import { DeleteOutlined, DownloadOutlined, PauseOutlined, PlusOutlined, ReloadOutlined, RetweetOutlined, SyncOutlined } from '@ant-design/icons-vue'

const router=useRouter();const rows=ref<any[]>([]);const total=ref(0);const page=ref(1);const size=ref(20);const loading=ref(false);const open=ref(false);const saving=ref(false);const selected=ref<string[]>([]);const mode=ref<'options'|'policy'>('options');const policies=ref<any[]>([]);const scopes=ref<any[]>([]);const syncOpen=ref(false);const syncTask=ref<any>();const syncScope=ref('')
const deleteOpen=ref(false);const deleteIds=ref<string[]>([]);const deleteData=ref(false);const deleting=ref(false)
const filter=reactive({name:'',target:'',status:''})
const defaults={name:'',target:'',task_tag:'task',policy_id:'',result_set_id:'',domain_brute:true,domain_brute_type:'test',port_scan:true,port_scan_type:'test',service_detection:false,service_brute:false,os_detection:false,site_identify:true,site_capture:false,file_leak:false,search_engines:false,site_spider:false,arl_search:false,alt_dns:false,ssl_cert:false,dns_query_plugin:false,skip_scan_cdn_ip:true,nuclei_scan:false,findvhost:false,web_info_hunter:false}
const form=reactive({...defaults})
const doneStatuses=['done','stop','error'];const selectedRows=computed(()=>rows.value.filter(x=>selected.value.includes(x._id)))
async function load(){loading.value=true;try{const data=await apiRequest<any>('/api/task/'+queryString({page:page.value,size:size.value,...filter}));rows.value=data.items||[];total.value=data.total||0;selected.value=[]}catch(e){message.error((e as Error).message)}finally{loading.value=false}}
async function loadReferences(){const [p,s]=await Promise.all([apiRequest<any>('/api/policy/?page=1&size=100'),apiRequest<any>('/api/asset_scope/?page=1&size=100')]);policies.value=p.items||[];scopes.value=s.items||[]}
function showCreate(){Object.assign(form,defaults);mode.value='options';open.value=true;loadReferences().catch(e=>message.error(e.message))}
async function createTask(){if(!form.name.trim())return message.error('请输入任务名');if(mode.value==='options'&&!form.target.trim())return message.error('请输入扫描目标');if(mode.value==='policy'&&!form.policy_id)return message.error('请选择扫描策略');if(mode.value==='policy'&&form.task_tag==='task'&&!form.target.trim())return message.error('资产发现任务必须填写目标');if(mode.value==='policy'&&form.task_tag==='risk_cruising'&&!form.target.trim()&&!form.result_set_id.trim())return message.error('风险巡航必须填写目标或结果集 ID');saving.value=true;try{const endpoint=mode.value==='policy'?'/api/task/policy/':'/api/task/';const body=mode.value==='policy'?{name:form.name.trim(),target:form.target.trim(),task_tag:form.task_tag,policy_id:form.policy_id,result_set_id:form.result_set_id.trim()}:Object.fromEntries(Object.entries(form).filter(([key])=>!['task_tag','policy_id','result_set_id'].includes(key)));await apiRequest(endpoint,{method:'POST',body:JSON.stringify(body)});message.success('任务已下发');open.value=false;await load()}catch(e){message.error((e as Error).message)}finally{saving.value=false}}
async function operate(action:'stop'|'restart', ids=selected.value){if(!ids.length)return;await apiRequest(action==='stop'?'/api/task/batch_stop/':'/api/task/restart/',{method:'POST',body:JSON.stringify({task_id:ids})});message.success(action==='stop'?'任务已停止':'任务已重新下发');await load()}
function remove(ids=selected.value){if(!ids.length)return;deleteIds.value=[...ids];deleteData.value=false;deleteOpen.value=true}
async function confirmRemove(){deleting.value=true;try{await apiRequest('/api/task/delete/',{method:'POST',body:JSON.stringify({task_id:deleteIds.value,del_task_data:deleteData.value})});message.success('任务已删除');deleteOpen.value=false;await load()}catch(e){message.error((e as Error).message)}finally{deleting.value=false}}
async function openSync(record:any){syncTask.value=record;syncScope.value='';syncOpen.value=true;try{const data=await apiRequest<any>('/api/task/sync_scope/'+queryString({target:record.target}));scopes.value=data.items||[]}catch{if(!scopes.value.length)await loadReferences()}}
async function sync(){await apiRequest('/api/task/sync/',{method:'POST',body:JSON.stringify({task_id:syncTask.value._id,scope_id:syncScope.value})});syncOpen.value=false;message.success('同步任务已提交');await load()}
async function exportSelected(type:string){if(!selected.value.length)return message.info('请先选择任务');try{await downloadRequest(`/api/batch_export/${type}/`,`${type}.txt`,{method:'POST',body:JSON.stringify({task_id:selected.value})})}catch(e){message.error((e as Error).message)}}
function rowAction(action:string,record:any){if(action==='detail')router.push(`/tasks/${record._id}`);if(action==='stop')operate('stop',[record._id]);if(action==='restart')operate('restart',[record._id]);if(action==='delete')remove([record._id]);if(action==='sync')openSync(record)}
const columns=[{title:'状态',dataIndex:'status',width:105},{title:'任务名',dataIndex:'name'},{title:'目标',dataIndex:'target'},{title:'类型',dataIndex:'type',width:90},{title:'开始时间',dataIndex:'start_time',width:155},{title:'统计',dataIndex:'statistic',width:160},{title:'操作',key:'action',width:210}]
onMounted(()=>{load();loadReferences().catch(()=>{})})
</script>
<template><section class="page"><PageHeader eyebrow="RECON / TASKS" title="侦察任务" description="使用完整扫描参数或既有策略下发任务，并批量停止、重启、删除、同步和导出结果。"><a-button @click="load"><ReloadOutlined/>刷新</a-button><a-dropdown><a-button :disabled="!selected.length"><DownloadOutlined/>导出结果</a-button><template #overlay><a-menu @click="({key}:any)=>exportSelected(key)"><a-menu-item v-for="type in ['domain','ip','ip_port','site','url','wih']" :key="type">{{type}}</a-menu-item></a-menu></template></a-dropdown><a-button type="primary" @click="showCreate"><PlusOutlined/>下发任务</a-button></PageHeader>
<div class="data-panel"><div class="query-strip task-filters"><a-input v-model:value="filter.name" placeholder="任务名" allow-clear/><a-input v-model:value="filter.target" placeholder="目标" allow-clear/><a-select v-model:value="filter.status" placeholder="全部状态" allow-clear :options="['waiting','running','done','error','stop'].map(value=>({value}))"/><a-button @click="page=1;load()">筛选</a-button><span><b>{{total}}</b> 个任务</span></div><div class="batch-bar" v-if="selected.length"><b>已选 {{selected.length}} 项</b><a-button size="small" @click="operate('stop')"><PauseOutlined/>停止</a-button><a-button size="small" @click="operate('restart')"><RetweetOutlined/>重启</a-button><a-button size="small" danger @click="remove()"><DeleteOutlined/>删除</a-button></div>
<a-table :columns="columns" :data-source="rows" :loading="loading" :pagination="false" row-key="_id" :scroll="{x:1100}" :row-selection="{selectedRowKeys:selected,onChange:(keys:(string|number)[])=>selected=keys.map(String)}"><template #bodyCell="{column,record}"><template v-if="column.key==='action'"><a-space><a @click="rowAction('detail',record)">详情</a><a v-if="!doneStatuses.includes(record.status)" @click="rowAction('stop',record)">停止</a><a v-else @click="rowAction('restart',record)">重启</a><a v-if="record.type==='domain'&&doneStatuses.includes(record.status)" @click="rowAction('sync',record)">同步</a><a v-if="doneStatuses.includes(record.status)" class="danger-link" @click="rowAction('delete',record)">删除</a></a-space></template><a-tag v-else-if="column.dataIndex==='status'" :color="record.status==='done'?'green':record.status==='error'?'red':record.status==='stop'?'default':'blue'">{{record.status}}</a-tag><span v-else-if="column.dataIndex==='statistic'" class="cell-value">域名 {{record.statistic?.domain_cnt||0}} · 站点 {{record.statistic?.site_cnt||0}}</span></template></a-table><a-pagination :current="page" :total="total" :page-size="size" show-size-changer @change="(n:number,s:number)=>{page=n;size=s;load()}"/></div>
<a-drawer v-model:open="open" title="下发侦察任务" width="min(720px,96vw)"><a-form layout="vertical" @finish="createTask"><a-segmented v-model:value="mode" :options="[{label:'自定义参数',value:'options'},{label:'扫描策略',value:'policy'}]" block/><a-form-item label="任务名" required><a-input v-model:value="form.name" maxlength="120"/></a-form-item><a-form-item label="目标" :required="form.task_tag==='task'" extra="支持域名、IP、CIDR；使用逗号、空格或换行分隔。"><a-textarea v-model:value="form.target" :rows="5"/></a-form-item>
<template v-if="mode==='policy'"><div class="form-grid"><a-form-item label="任务类别" required><a-select v-model:value="form.task_tag" :options="[{value:'task',label:'资产发现'},{value:'risk_cruising',label:'风险巡航'}]"/></a-form-item><a-form-item label="扫描策略" required><a-select v-model:value="form.policy_id" show-search option-filter-prop="label" :options="policies.map(x=>({value:x._id,label:x.name}))"/></a-form-item></div><a-form-item v-if="form.task_tag==='risk_cruising'" label="结果集 ID" extra="目标或结果集至少填写一项"><a-input v-model:value="form.result_set_id"/></a-form-item></template>
<template v-else><a-divider>域名与端口</a-divider><div class="form-grid"><a-form-item label="域名爆破"><a-switch v-model:checked="form.domain_brute"/></a-form-item><a-form-item label="爆破字典"><a-select v-model:value="form.domain_brute_type" :options="['test','big'].map(value=>({value,label:value}))"/></a-form-item><a-form-item label="端口扫描"><a-switch v-model:checked="form.port_scan"/></a-form-item><a-form-item label="端口范围"><a-select v-model:value="form.port_scan_type" :options="['test','top100','top1000','all'].map(value=>({value,label:value}))"/></a-form-item></div><a-divider>发现能力</a-divider><div class="switch-grid"><label v-for="([key,label]) in [['alt_dns','智能 DNS 字典'],['arl_search','ARL 历史查询'],['dns_query_plugin','DNS 插件查询'],['search_engines','搜索引擎'],['site_spider','站点爬虫'],['site_identify','站点识别'],['site_capture','站点截图'],['service_detection','服务识别'],['service_brute','服务弱口令'],['os_detection','操作系统识别'],['ssl_cert','SSL 证书'],['file_leak','文件泄漏'],['nuclei_scan','Nuclei'],['findvhost','Host 碰撞'],['web_info_hunter','Web 信息猎手'],['skip_scan_cdn_ip','跳过 CDN IP']]" :key="key"><a-switch v-model:checked="form[key as keyof typeof form]"/>{{label}}</label></div></template><div class="drawer-actions"><a-button @click="open=false">取消</a-button><a-button type="primary" html-type="submit" :loading="saving">确认下发</a-button></div></a-form></a-drawer>
<a-modal v-model:open="syncOpen" title="同步任务资产到资产组" ok-text="开始同步" :ok-button-props="{disabled:!syncScope}" @ok="sync"><p>{{syncTask?.target}}</p><a-select v-model:value="syncScope" style="width:100%" placeholder="选择包含该目标的资产组" :options="scopes.map(x=>({value:x._id,label:`${x.name} · ${x.scope}`}))"/></a-modal><a-modal v-model:open="deleteOpen" title="删除任务" ok-text="确认删除" ok-type="danger" :confirm-loading="deleting" @ok="confirmRemove"><p>将删除 {{deleteIds.length}} 个已结束任务，此操作无法恢复。</p><a-checkbox v-model:checked="deleteData">同时删除任务产生的全部资产与结果</a-checkbox></a-modal></section></template>
